use crate::config::Config;
use std::fs;
use std::io;
use std::path::PathBuf;
use std::process::{Command, Stdio};

const UNIT_NAME: &str = "ramo-daemon.service";

pub fn unit_dir() -> PathBuf {
    Config::config_base().join("systemd").join("user")
}

pub fn unit_path() -> PathBuf {
    unit_dir().join(UNIT_NAME)
}

pub fn is_installed() -> bool {
    unit_path().is_file()
}

pub fn under_systemd() -> bool {
    std::env::var("INVOCATION_ID").is_ok()
}

fn systemctl(args: &[&str]) -> io::Result<bool> {
    match Command::new("systemctl")
        .arg("--user")
        .args(args)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
    {
        Ok(status) => Ok(status.success()),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(e),
    }
}

pub fn stop() -> bool {
    systemctl(&["stop", UNIT_NAME]).unwrap_or(false)
}

fn write_service_file() -> io::Result<PathBuf> {
    let dir = unit_dir();
    fs::create_dir_all(&dir)?;

    let exe = std::env::current_exe()?;
    let unit = format!(
        "# managed by ramo, regenerated by `ramo daemon install`\n\
         [Unit]\n\
         Description=Ramo session picker daemon\n\
         \n\
         [Service]\n\
         Type=simple\n\
         ExecStart=\"{}\" daemon start\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
        exe.display()
    );
    let path = unit_path();
    fs::write(&path, unit)?;
    Ok(path)
}

fn opt_out_path() -> PathBuf {
    Config::config_base().join("ramo").join("no-autostart")
}

pub enum InstallMode {
    Interactive,
    Background,
}

pub fn install(mode: InstallMode) -> io::Result<()> {
    let quiet = matches!(mode, InstallMode::Background);
    if quiet && (is_installed() || opt_out_path().is_file()) {
        return Ok(());
    }
    let path = write_service_file()?;
    if !quiet {
        let _ = fs::remove_file(opt_out_path());
        println!("wrote {}", path.display());
    }

    // Quiet path is the cold-spawn autostart: enable only, the spawner
    // already started this boot's daemon so --now would race it.
    let enable: &[&str] = if quiet {
        &["enable", UNIT_NAME]
    } else {
        &["enable", "--now", UNIT_NAME]
    };
    let tell = |err: bool, msg: String| {
        if !quiet {
            if err {
                eprintln!("{msg}");
            } else {
                println!("{msg}");
            }
        }
    };
    match systemctl(&["daemon-reload"]) {
        Ok(true) => match systemctl(enable) {
            Ok(true) => tell(
                false,
                format!("enabled and started {UNIT_NAME} — the daemon will now start at login"),
            ),
            Ok(false) => tell(
                true,
                format!(
                    "warning: `systemctl --user enable --now {UNIT_NAME}` failed — run it manually"
                ),
            ),
            Err(e) => tell(true, format!("warning: failed to run systemctl: {e}")),
        },
        Ok(false) => tell(
            true,
            "warning: `systemctl --user daemon-reload` failed — run it manually".into(),
        ),
        Err(e) => tell(
            true,
            format!("warning: systemctl not available ({e}) — unit installed but not enabled"),
        ),
    }
    Ok(())
}

pub fn uninstall() -> io::Result<()> {
    let _ = systemctl(&["stop", UNIT_NAME]);
    let _ = systemctl(&["disable", UNIT_NAME]);
    // Stick: keep auto-install from re-enabling login start behind the
    // user's back. `install` removes it; purge --with-config wipes the dir.
    let _ = fs::create_dir_all(Config::config_base().join("ramo"));
    let _ = fs::write(opt_out_path(), "run `ramo daemon install` to start at login\n");
    let path = unit_path();
    match fs::remove_file(&path) {
        Ok(()) => println!("removed {}", path.display()),
        Err(e) if e.kind() == io::ErrorKind::NotFound => {}
        Err(e) => eprintln!("failed to remove {}: {e}", path.display()),
    }

    let _ = systemctl(&["daemon-reload"]);
    Ok(())
}
