use crate::config::Config;
use std::fs;
use std::io;
use std::path::PathBuf;
use std::process::Command;

const UNIT_NAME: &str = "ramo-daemon.service";

pub fn unit_name() -> &'static str {
    UNIT_NAME
}

pub fn unit_dir() -> PathBuf {
    Config::config_base().join("systemd").join("user")
}

pub fn unit_path() -> PathBuf {
    unit_dir().join(unit_name())
}

pub fn is_installed() -> bool {
    unit_path().is_file()
}

pub fn under_systemd() -> bool {
    std::env::var("INVOCATION_ID").is_ok()
}

fn systemctl(args: &[&str]) -> io::Result<bool> {
    match Command::new("systemctl").arg("--user").args(args).status() {
        Ok(status) => Ok(status.success()),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(e),
    }
}

pub fn stop() -> bool {
    systemctl(&["stop", unit_name()]).unwrap_or(false)
}

pub fn install() -> io::Result<()> {
    let dir = unit_dir();
    fs::create_dir_all(&dir)?;

    let exe = std::env::current_exe()?;
    let unit = format!(
        "# managed by ramo, regenerated by `ramo daemon install`\n\
         [Unit]\n\
         Description=Ramo session picker daemon\n\
         \n\
         [Service]\n\
         Type=simple\n\
         ExecStart=\"{}\" daemon start\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
        exe.display()
    );
    let path = unit_path();
    fs::write(&path, unit)?;
    println!("wrote {}", path.display());

    match systemctl(&["daemon-reload"]) {
        Ok(true) => match systemctl(&["enable", "--now", unit_name()]) {
            Ok(true) => println!(
                "enabled and started {} — the daemon will now start at login",
                unit_name()
            ),
            Ok(false) => eprintln!(
                "warning: `systemctl --user enable --now {}` failed — run it manually",
                unit_name()
            ),
            Err(e) => eprintln!("warning: failed to run systemctl: {e}"),
        },
        Ok(false) => eprintln!(
            "warning: `systemctl --user daemon-reload` failed — run it manually"
        ),
        Err(e) => eprintln!(
            "warning: systemctl not available ({e}) — unit installed but not enabled"
        ),
    }
    Ok(())
}

pub fn uninstall() -> io::Result<()> {
    let _ = systemctl(&["stop", unit_name()]);
    let _ = systemctl(&["disable", unit_name()]);

    let path = unit_path();
    match fs::remove_file(&path) {
        Ok(()) => println!("removed {}", path.display()),
        Err(e) if e.kind() == io::ErrorKind::NotFound => {}
        Err(e) => eprintln!("failed to remove {}: {e}", path.display()),
    }

    let _ = systemctl(&["daemon-reload"]);
    Ok(())
}
